compressionLevel: 9

nodeLinker: node-modules # pnpm/pnp/node-modules
nmMode: hardlinks-global

# Plug N' Play
pnpEnableEsmLoader: true
pnpMode: strict
pnpFallbackMode: dependencies-only

# Registry
npmRegistryServer: "https://registry.yarnpkg.com"
npmPublishRegistry: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
progressBarStyle: default
