name: "install-packages"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node@18.x
        uses: actions/setup-node@v3.8.2
        with:
          node-version: 18.x
          cache: "yarn"

      - run: yarn install --frozen-lockfile # optional, --immutable
